### ISSUE TITLE
Failed to load the RubyMotion package

### ISSUE THREAD

**Issue by nicjp** [satococoa/atom-rubymotion#22]
[Enter steps to reproduce below:]
1. Upgrade to Atom 0.187.0 from 0.186.0
2. Launch Atom
3. Error message displayed. 

No user intervention occurred to produce this error. 

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [RubyMotion](https://github.com/satococoa/atom-rubymotion) package, v0.6.2
### Stack Trace

Failed to load the RubyMotion package

```
At Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/snippets'

Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/snippets'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/nic/.atom/packages/RubyMotion/lib/rubymotion.coffee:16:14)
    at Object.<anonymous> (/Users/nic/.atom/packages/RubyMotion/lib/rubymotion.coffee:137:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "oceans16-atom"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
RubyMotion, v0.6.2
language-haml, v0.15.0
oceans16-atom, v16.0.0
raml, v0.1.0

# Dev
No dev packages
```

**Comment by otzy007** [comment]
Same problem for me.
It happens when I start atom 0.187.0 

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [RubyMotion](https://github.com/satococoa/atom-rubymotion) package, v0.6.2

### Stack Trace

Failed to load the RubyMotion package

```
At Cannot find module '/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/snippets'

Error: Cannot find module '/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/snippets'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/andrei/.atom/packages/RubyMotion/lib/rubymotion.coffee:16:14)
    at Object.<anonymous> (/Users/andrei/.atom/packages/RubyMotion/lib/rubymotion.coffee:137:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
RubyMotion, v0.6.2
autocomplete-css, v0.4.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
cucumber, v0.4.1
git-log, v0.3.0
github-issues, v0.3.0
language-latex, v0.4.1
language-rust, v0.4.2

# Dev
No dev packages
```
