### ISSUE TITLE
Failed to load the RubyMotion package

### ISSUE THREAD

**Issue by NullVoxPopuli** [satococoa/atom-rubymotion#24]
[Enter steps to reproduce below:]
1. try to install rubymotion

**Atom Version**: 0.187.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [RubyMotion](https://github.com/satococoa/atom-rubymotion) package, v0.6.2
### Stack Trace

Failed to load the RubyMotion package

```
At Cannot find module '/usr/share/atom/resources/app/node_modules/snippets'

Error: Cannot find module '/usr/share/atom/resources/app/node_modules/snippets'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/lprestonsegoiii/.atom/packages/RubyMotion/lib/rubymotion.coffee:8:12)
  at Object.<anonymous> (/home/lprestonsegoiii/.atom/packages/RubyMotion/lib/rubymotion.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:464:30)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -2:12.1 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
RubyMotion, v0.6.2
autocomplete-ruby, v0.0.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by otzy007** [comment]
Happens to me too while starting Atom

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [RubyMotion](https://github.com/satococoa/atom-rubymotion) package, v0.6.2

### Stack Trace

Failed to load the RubyMotion package

```
At Cannot find module '/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/snippets'

Error: Cannot find module '/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/snippets'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/andrei/.atom/packages/RubyMotion/lib/rubymotion.coffee:16:14)
    at Object.<anonymous> (/Users/andrei/.atom/packages/RubyMotion/lib/rubymotion.coffee:137:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
RubyMotion, v0.6.2
autocomplete-css, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
cucumber, v0.4.1
git-log, v0.3.0
github-issues, v0.3.0
language-latex, v0.4.1
language-rust, v0.4.2

# Dev
No dev packages
```

**Comment by wwvuillemot** [comment]
1. FWIW, I have the same issue
2. I just launch Atom from the command-line (e.g. `atom`)
3. I get the error if I start up directly through Finder, too

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [RubyMotion](https://github.com/satococoa/atom-rubymotion) package, v0.6.2

### Stack Trace

Failed to load the RubyMotion package

```
At Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/snippets'

Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/snippets'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/wwv/.atom/packages/RubyMotion/lib/rubymotion.coffee:16:14)
    at Object.<anonymous> (/Users/wwv/.atom/packages/RubyMotion/lib/rubymotion.coffee:137:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
RubyMotion, v0.6.2
linter-rubocop, v0.2.2

# Dev
No dev packages
```

**Comment by TerribleDev** [comment]
:+1:

**Comment by matthewsinclair** [comment]
:+1:

**Comment by satococoa** [comment]
Sorry for late response.

Thank you for your feedback. I'll look into this in this weekend.
But I am not using RubyMotion now, so any Pull Requests will be very appreciated.

**Comment by anildigital** [comment]
I am facing this issue too.

**Comment by ChristianBagley** [comment]
I'm working on a fix for this now, will update later this evening, hopefully with a pull request. I believe I found the issue, though.

**Comment by markrickert** [comment]
Any update on this @ChristianBagley?

**Comment by matthewsinclair** [comment]
Sadly, I'm going to have to disable the RubyMotion Atom package until this fixed. In any case, thanks for the efforts to date, folks. I know how hard it is to get time to fix OSS stuff like this when it's not a top-line priority.

**Comment by ChristianBagley** [comment]
@markrickert My apologies for the delay. Things got hectic with my schedule, had to divert my attention. I will get back to working on a fix for this, or a least try to narrow down the problem, soon. Once I get home I can post the relevant code where I think the problem is, and get some opinions on it - incase I'm totally off. 

@matthewsinclair Understandable Matthew, hopefully we can cook up a solution soon. I know I'm eager to get back to RubyMotion support in Atom.

**Comment by matthewsinclair** [comment]
Hey @ChristianBagley, thanks for taking the time! I was just trying to offer some words of support because I know how thankless this kind of task can be. Best of luck tracking down the problem. :)

**Comment by beatrixada** [comment]
Was this ever fixed?

**Comment by dgilperez** [comment]
Got hit by this as well. Any plans to fix this?

**Comment by nickyhajal** [comment]
Any updates on this?
